# Dev profile
%dev.quarkus.http.port=8090
%dev.quarkus.log.level=INFO

quarkus.http.port=8090
#quarkus.http.cors.enabled=true
#quarkus.http.host=0.0.0.0

# Database type
quarkus.datasource.db-kind=mysql
# Connection
quarkus.datasource.username=test
quarkus.datasource.password=test
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/test

# Disable Hibernate schema management
quarkus.hibernate-orm.database.generation=none

# Flyway configuration
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
# Optional: log SQL
quarkus.hibernate-orm.log.sql=true

# Dev convenience
%dev.quarkus.flyway.clean-at-start=true

# OpenAPI / Swagger
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.enabled=true

quarkus.datasource.devservices.enabled=true
quarkus.micrometer.enabled=false







# ---- Camunda 8 / Zeebe local connection ----
camunda.client.mode=self-managed
camunda.client.zeebe.grpc-address=http://localhost:26500

# Disable security for local dev
camunda.client.auth.enabled=false
camunda.client.zeebe.tls.enabled=false